export { Nav } from './Nav';
export { Hero } from './Hero';
export { HowItWorks } from './HowItWorks';
export { Features } from './Features';
export { Pricing } from './Pricing';
export { FAQ } from './FAQ';
export { FinalCTA } from './FinalCTA';
export { Footer } from './Footer';
export { TerminalLanding } from './TerminalLanding';
export { EditorialLanding } from './EditorialLanding';
export { default as FolioLanding } from './FolioLanding';
